[package]
name = "localdex"
version = "0.4.4"
edition = "2024"

[dependencies]
ignore = "0.4.25"
anyhow = "1.0.101"
colored = "3.1.1"
dirs = "6.0.0"
parex = "0.3.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.1"
chrono = "0.4.43"

[profile.release]
debug = true
