[package]
name = "localdex"
version = "0.1.0"
edition = "2024"

[dependencies]
aho-corasick = "1.1.4"
anyhow = "1.0.101"
colored = "3.1.1"
dirs = "6.0.0"
ignore = "0.4.25"
num_cpus = "1.17.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.1"
